### ISSUE TITLE
last_run.json not found with v1.5.0

### ISSUE THREAD

**Issue by anit** [aki77/simplecov-report-action#27]
The new version 1.5.0 has changed node version of this package from 12 to 16 and it seems to be the root cause of an error we have been facing:

```
Error: Cannot find module '/home/runner/work/orgapp/orgapp/coverage/.last_run.json'
Require stack:
- /home/runner/work/_actions/aki77/simplecov-report-action/v1/dist/index.js
```

This is the version of Github action that was downloaded to us: 
```
Download action repository 'aki77/simplecov-report-action@v[1](https://github.com/****/****/runs/70378****?check_suite_focus=true#step:16:1)' (SHA:a06b28c81eb8254618c93eebd09956767373b07e)
```

**Comment by aki77** [comment]
If I set `aki77/simplecov-report-action@v1.4.1` will it succeed?

**Comment by anit** [comment]
@aki77  Yes. It did. We pinned it to 1.4.1 and our actions are running fine now.

**Comment by aki77** [comment]
@anit 

It does not seem to reproduce in my environment.
Can you provide a minimal reproduction repository?

**Comment by aki77** [comment]
I have checked with minimal settings and it seems to succeed.

https://github.com/aki77/rails-github-actions-example/actions/runs/2558418038

https://github.com/aki77/rails-github-actions-example/commit/3c0526556d4a97ce77bf9075ca01b806f9962a2c

**Comment by aki77** [comment]
This is due to the absence of `coverage/.last_run.json`.
Please review the simplecov configuration.

In v1.4.1, the entire process is skipped because it is unsupported except for PR events.
