### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by joshuamcginnis** [aki77/simplecov-report-action#30]
Hi. I'm using the default `GITHUB_TOKEN` permissions set and am not seeing the simplecov report from the GH Actions bot. Could you confirm the permissions necessary for the coverage to be properly shown on a PR? Thank you!

**Comment by aki77** [comment]
Can you provide a mini repo ?

**Comment by joshuamcginnis** [comment]
Here's the actual one, it's fairly open: https://github.com/joshuamcginnis/postalpast

**Comment by aki77** [comment]
I think it's because `github.context.issue.number` doesn't exist.

https://github.com/aki77/simplecov-report-action/blob/aa7e761094e4ae7487959988f26657b1ce3b61e5/src/report.ts#L12

https://github.com/joshuamcginnis/postalpast/actions/runs/3019473897

**Comment by joshuamcginnis** [comment]
Hm. The PR has a referenced issue but the coverage bot still isn't reporting on the PR.
